//! IR → compilable source skeleton (deterministic, non-AI).
//!
//! Walks a [`Document`] and emits a stub in the chosen [`Language`]:
//! signatures are real, bodies are empty, notes/comments carry documentation.
//! This is the **UML → Code** half of the code ↔ UML story.

use super::Language;
use crate::class::{Class, ClassDiagram, ClassMember, Relation, RelationKind};
use crate::diagram::{Diagram as FcDiagram, Node, NodeShape, Subgraph};
use crate::er::{Attribute, Cardinality, ErDiagram};
use crate::ir::{Diagram, Document};
use crate::sequence::SequenceDiagram;
use crate::state::{StateDiagram, StateNodeKind, START_END};

/// Emit a source skeleton for `doc` in `lang`. The output is always
/// compilable when paired with the appropriate toolchain (cargo / tsc).
pub fn skeleton(doc: &Document, lang: Language) -> String {
    match lang {
        Language::Rust => rust::emit(doc),
        Language::TypeScript => typescript::emit(doc),
    }
}

// ---------------------------------------------------------------------------
// Rust
// ---------------------------------------------------------------------------

mod rust {
    use super::*;

    pub fn emit(doc: &Document) -> String {
        let mut out = String::new();
        out.push_str("// Generated by `diagram generate-skeleton` (non-AI, deterministic).\n");
        out.push_str("// Edit freely; signatures come from the canonical IR.\n\n");
        for diag in &doc.diagrams {
            emit_diagram(diag, &mut out);
        }
        if out.ends_with("\n\n") {
            out.pop();
        }
        out
    }

    fn emit_diagram(diag: &Diagram, out: &mut String) {
        match diag {
            Diagram::Class(c) => emit_class(c, out),
            Diagram::Flowchart(f) => emit_flowchart(f, out),
            Diagram::Sequence(s) => emit_sequence(s, out),
            Diagram::State(s) => emit_state(s, out),
            Diagram::Er(e) => emit_er(e, out),
            Diagram::Gantt(_) => {
                out.push_str("// Gantt charts do not map to a skeleton; nothing to emit.\n\n");
            }
        }
    }

    fn emit_class(cd: &ClassDiagram, out: &mut String) {
        // 1. Type declarations.
        for c in &cd.classes {
            emit_class_decl(c, out);
        }
        // 2. Relation-based fields (composition / aggregation / association /
        //    link / dependency) attached to the `from` side. Inheritance /
        //    Realization become `impl` blocks.
        let mut rels_by_from: std::collections::HashMap<&str, Vec<&Relation>> =
            std::collections::HashMap::new();
        for r in &cd.relations {
            rels_by_from.entry(r.from.as_str()).or_default().push(r);
        }
        for c in &cd.classes {
            if let Some(rs) = rels_by_from.get(c.id.as_str()) {
                for r in rs {
                    match r.kind {
                        RelationKind::Inheritance | RelationKind::Realization => {
                            out.push_str(&format!(
                                "impl {} for {} {{}}\n\n",
                                type_ident(&r.to),
                                type_ident(&c.id)
                            ));
                        }
                        _ => {
                            out.push_str(&format!(
                                "    {} // {} {} ({})\n",
                                field_for_relation(r),
                                arrow_str(r.kind),
                                type_ident(&r.to),
                                cardinality(r)
                            ));
                        }
                    }
                }
            }
        }
        // 3. Notes as comments.
        for n in &cd.notes {
            out.push_str(&format!(
                "// note for {}: {}\n",
                type_ident(&n.target),
                n.text
            ));
        }
        if !cd.notes.is_empty() {
            out.push('\n');
        }
    }

    fn emit_class_decl(c: &Class, out: &mut String) {
        let stereo = c.stereotype.as_deref().unwrap_or("");
        let id = type_ident(&c.id);
        if stereo == "interface" {
            out.push_str(&format!("trait {id} {{\n"));
            for m in &c.members {
                if let Some(sig) = rust_method_sig(m) {
                    out.push_str(&format!("    {sig} {{ todo!() }}\n"));
                }
            }
            out.push_str("}\n\n");
            return;
        }
        if stereo == "enumeration" {
            out.push_str(&format!("enum {id} {{\n"));
            for m in &c.members {
                let variant = member_name(m);
                if !variant.is_empty() {
                    out.push_str(&format!("    {variant},\n"));
                }
            }
            out.push_str("}\n\n");
            return;
        }
        if stereo == "service" {
            // `service` is an `impl Trait for Type` block (Rust). Re-emit
            // it as a proper impl block so re-extraction sees the same
            // shape; members go inside the impl.
            if let Some((trait_name, type_name)) = split_impl_id(&c.id) {
                out.push_str(&format!("impl {trait_name} for {type_name} {{\n"));
                for m in &c.members {
                    if let Some(sig) = rust_method_sig(m) {
                        out.push_str(&format!("    {sig} {{ todo!() }}\n"));
                    }
                }
                out.push_str("}\n\n");
                return;
            }
            // Fall through: malformed id, emit as struct.
        }
        // Default: struct (with method signatures interleaved as `impl`).
        out.push_str(&format!("struct {id} {{\n"));
        for m in &c.members {
            if let Some(field) = rust_field_decl(m) {
                out.push_str(&format!("    pub {field},\n"));
            }
        }
        out.push_str("}\n\n");
        // Methods go in a separate impl block (or an inherent impl for
        // classes without an interface).
        let methods: Vec<_> = c.members.iter().filter_map(rust_method_sig).collect();
        if !methods.is_empty() {
            out.push_str(&format!("impl {id} {{\n"));
            for sig in methods {
                out.push_str(&format!("    {sig} {{ todo!() }}\n"));
            }
            out.push_str("}\n\n");
        }
    }

    fn emit_flowchart(fc: &FcDiagram, out: &mut String) {
        // Stable order: process subgraphs by appearance, then top-level nodes
        // not in any subgraph.
        let in_subgraph: std::collections::HashSet<&str> = fc
            .subgraphs
            .iter()
            .flat_map(|s| s.nodes.iter().map(|n| n.as_str()))
            .collect();
        for sg in &fc.subgraphs {
            emit_subgraph(sg, fc, out);
        }
        for n in &fc.nodes {
            if !in_subgraph.contains(n.id.as_str()) {
                emit_node_decl(n, out);
            }
        }
        for e in &fc.edges {
            out.push_str(&format!(
                "// {} {} {}{}\n",
                ident(&e.from),
                style_arrow(&e.style),
                ident(&e.to),
                if e.label.is_empty() {
                    String::new()
                } else {
                    format!(" // {}", e.label)
                }
            ));
        }
        if !fc.edges.is_empty() {
            out.push('\n');
        }
    }

    fn emit_subgraph(sg: &Subgraph, fc: &FcDiagram, out: &mut String) {
        let id = mod_ident(&sg.id);
        out.push_str(&format!("pub mod {id} {{\n"));
        for nid in &sg.nodes {
            if let Some(n) = fc.nodes.iter().find(|n| &n.id == nid) {
                emit_node_decl(n, out);
            }
        }
        out.push_str("}\n\n");
    }

    fn emit_node_decl(n: &Node, out: &mut String) {
        let id = ident(&n.id);
        let label = node_label(n);
        match n.shape {
            NodeShape::Stadium => {
                out.push_str(&format!("fn {id}() {{\n    // {label}\n    todo!()\n}}\n\n"));
            }
            NodeShape::Cylinder => {
                out.push_str(&format!("struct {id};\n"));
            }
            NodeShape::Diamond => {
                out.push_str(&format!("// decision: {id} ({label})\n"));
            }
            NodeShape::Circle => {
                out.push_str(&format!("// external: {id} ({label})\n"));
            }
            NodeShape::Hexagon | NodeShape::Rect => {
                out.push_str(&format!("const {id}_LABEL: &str = {label:?};\n"));
            }
        }
    }

    fn emit_sequence(s: &SequenceDiagram, out: &mut String) {
        // Each participant becomes a struct; each message becomes a method
        // signature on the receiver's struct.
        let mut methods: std::collections::HashMap<&str, Vec<String>> =
            std::collections::HashMap::new();
        for m in &s.messages {
            methods
                .entry(m.to.as_str())
                .or_default()
                .push(format!("    /// {} -> {}\n    fn {}(&self) {{}}\n", m.from, m.text, ident(&m.text)));
        }
        for p in &s.participants {
            if p.id == START_END {
                continue;
            }
            let id = type_ident(&p.id);
            out.push_str(&format!("struct {id} {{}}\n"));
            if let Some(ms) = methods.get(p.id.as_str()) {
                out.push_str(&format!("impl {id} {{\n"));
                for m in ms {
                    out.push_str(m);
                }
                out.push_str("}\n");
            }
            out.push('\n');
        }
        for n in &s.notes {
            out.push_str(&format!(
                "// note ({}): {}\n",
                note_placement(n.placement),
                n.text
            ));
        }
        if !s.notes.is_empty() {
            out.push('\n');
        }
    }

    fn emit_state(s: &StateDiagram, out: &mut String) {
        let mut variants: Vec<&str> = Vec::new();
        for st in &s.states {
            if matches!(st.kind, StateNodeKind::StartEnd) {
                continue;
            }
            variants.push(st.id.as_str());
        }
        if variants.is_empty() {
            out.push_str("// state diagram has no states.\n");
            return;
        }
        out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
        out.push_str("pub enum States {\n");
        for v in &variants {
            out.push_str(&format!("    {},\n", type_ident(v)));
        }
        out.push_str("}\n\n");
        out.push_str("// transitions:\n");
        for t in &s.transitions {
            out.push_str(&format!(
                "//   {} -> {} : {}\n",
                type_ident(&t.from),
                type_ident(&t.to),
                t.label
            ));
        }
        out.push('\n');
    }

    fn emit_er(e: &ErDiagram, out: &mut String) {
        for ent in &e.entities {
            let id = type_ident(&ent.id);
            out.push_str(&format!("struct {id} {{\n"));
            for a in &ent.attributes {
                let (ty, marker) = er_attr_marker(a);
                out.push_str(&format!("    {marker} {}: {ty},\n", ident(&a.name)));
            }
            out.push_str("}\n\n");
        }
        for r in &e.relationships {
            out.push_str(&format!(
                "// {} {}--{} {}\n",
                type_ident(&r.from),
                r.from_card.symbol(),
                r.to_card.symbol(),
                type_ident(&r.to),
            ));
        }
        if !e.relationships.is_empty() {
            out.push('\n');
        }
    }
}

// ---------------------------------------------------------------------------
// TypeScript
// ---------------------------------------------------------------------------

mod typescript {
    use super::*;

    pub fn emit(doc: &Document) -> String {
        let mut out = String::new();
        out.push_str(
            "// Generated by `diagram generate-skeleton` (non-AI, deterministic).\n",
        );
        out.push_str("// Edit freely; signatures come from the canonical IR.\n\n");
        for diag in &doc.diagrams {
            emit_diagram(diag, &mut out);
        }
        if out.ends_with("\n\n") {
            out.pop();
        }
        out
    }

    fn emit_diagram(diag: &Diagram, out: &mut String) {
        match diag {
            Diagram::Class(c) => emit_class(c, out),
            Diagram::Flowchart(f) => emit_flowchart(f, out),
            Diagram::Sequence(s) => emit_sequence(s, out),
            Diagram::State(s) => emit_state(s, out),
            Diagram::Er(e) => emit_er(e, out),
            Diagram::Gantt(_) => {
                out.push_str("// Gantt charts do not map to a skeleton; nothing to emit.\n\n");
            }
        }
    }

    fn emit_class(cd: &ClassDiagram, out: &mut String) {
        // Bucket relations by `from` for inheritance/realization vs fields.
        let mut inheritance: std::collections::HashMap<&str, Vec<&Relation>> =
            std::collections::HashMap::new();
        let mut fields: std::collections::HashMap<&str, Vec<&Relation>> =
            std::collections::HashMap::new();
        for r in &cd.relations {
            match r.kind {
                RelationKind::Inheritance | RelationKind::Realization => {
                    inheritance.entry(r.from.as_str()).or_default().push(r);
                }
                _ => {
                    fields.entry(r.from.as_str()).or_default().push(r);
                }
            }
        }
        for c in &cd.classes {
            let inheritance = inheritance.get(c.id.as_str()).map(Vec::as_slice);
            let fields = fields.get(c.id.as_str()).map(Vec::as_slice);
            emit_class_decl(c, inheritance, fields, out);
        }
        for n in &cd.notes {
            out.push_str(&format!(
                "// note for {}: {}\n",
                type_ident(&n.target),
                n.text
            ));
        }
        if !cd.notes.is_empty() {
            out.push('\n');
        }
    }

    fn emit_class_decl(
        c: &Class,
        inheritance: Option<&[&Relation]>,
        fields: Option<&[&Relation]>,
        out: &mut String,
    ) {
        let stereo = c.stereotype.as_deref().unwrap_or("");
        let id = type_ident(&c.id);
        let extends = inheritance
            .map(|rs| rs.iter().filter(|r| r.kind == RelationKind::Inheritance).map(|r| type_ident(&r.to)).collect::<Vec<_>>().join(", "))
            .unwrap_or_default();
        let implements = inheritance
            .map(|rs| rs.iter().filter(|r| r.kind == RelationKind::Realization).map(|r| type_ident(&r.to)).collect::<Vec<_>>().join(", "))
            .unwrap_or_default();
        let mut head = format!("class {id}");
        if !extends.is_empty() {
            head.push_str(&format!(" extends {extends}"));
        }
        if !implements.is_empty() {
            head.push_str(&format!(" implements {implements}"));
        }
        if stereo == "interface" {
            out.push_str(&format!("interface {id} {{\n"));
            for m in &c.members {
                if let Some(sig) = ts_method_sig(m, true) {
                    out.push_str(&format!("    {sig};\n"));
                }
            }
            out.push_str("}\n\n");
            return;
        }
        if stereo == "enumeration" {
            out.push_str(&format!("enum {id} {{\n"));
            for m in &c.members {
                let variant = member_name(m);
                if !variant.is_empty() {
                    out.push_str(&format!("    {variant},\n"));
                }
            }
            out.push_str("}\n\n");
            return;
        }
        out.push_str(&format!("{head} {{\n"));
        for m in &c.members {
            if let Some(field) = ts_field_decl(m) {
                out.push_str(&format!("    {field};\n"));
            }
        }
        if let Some(fs) = fields {
            for r in fs {
                out.push_str(&format!(
                    "    {}: {}; // {} {} ({})\n",
                    ident(&r.to),
                    type_ident(&r.to),
                    arrow_str(r.kind),
                    cardinality(r),
                    if r.label.is_empty() { String::new() } else { format!(" : {}", r.label) }
                ));
            }
        }
        for m in &c.members {
            if let Some(sig) = ts_method_sig(m, false) {
                out.push_str(&format!("    {sig} {{\n        // TODO\n    }}\n"));
            }
        }
        out.push_str("}\n\n");
    }

    fn emit_flowchart(fc: &FcDiagram, out: &mut String) {
        let in_subgraph: std::collections::HashSet<&str> = fc
            .subgraphs
            .iter()
            .flat_map(|s| s.nodes.iter().map(|n| n.as_str()))
            .collect();
        for sg in &fc.subgraphs {
            emit_subgraph(sg, fc, out);
        }
        for n in &fc.nodes {
            if !in_subgraph.contains(n.id.as_str()) {
                emit_node_decl(n, out);
            }
        }
        for e in &fc.edges {
            out.push_str(&format!(
                "// {} {} {}{}\n",
                ident(&e.from),
                style_arrow(&e.style),
                ident(&e.to),
                if e.label.is_empty() {
                    String::new()
                } else {
                    format!(" // {}", e.label)
                }
            ));
        }
        if !fc.edges.is_empty() {
            out.push('\n');
        }
    }

    fn emit_subgraph(sg: &Subgraph, fc: &FcDiagram, out: &mut String) {
        let id = mod_ident(&sg.id);
        out.push_str(&format!("export namespace {id} {{\n"));
        for nid in &sg.nodes {
            if let Some(n) = fc.nodes.iter().find(|n| &n.id == nid) {
                emit_node_decl(n, out);
            }
        }
        out.push_str("}\n\n");
    }

    fn emit_node_decl(n: &Node, out: &mut String) {
        let id = ident(&n.id);
        let label = node_label(n);
        match n.shape {
            NodeShape::Stadium => {
                out.push_str(&format!(
                    "export function {id}(): void {{\n    // {label}\n}}\n\n"
                ));
            }
            NodeShape::Cylinder => {
                out.push_str(&format!("export interface {id} {{}}\n\n"));
            }
            NodeShape::Diamond => {
                out.push_str(&format!("// decision: {id} ({label})\n"));
            }
            NodeShape::Circle => {
                out.push_str(&format!("// external: {id} ({label})\n"));
            }
            NodeShape::Hexagon | NodeShape::Rect => {
                out.push_str(&format!("export const {id}: string = {label:?};\n"));
            }
        }
    }

    fn emit_sequence(s: &SequenceDiagram, out: &mut String) {
        let mut methods: std::collections::HashMap<&str, Vec<String>> =
            std::collections::HashMap::new();
        for m in &s.messages {
            let method = format!("    {}(args?: unknown): void {{}};\n", ident(&m.text));
            methods.entry(m.to.as_str()).or_default().push(method);
        }
        for p in &s.participants {
            if p.id == START_END {
                continue;
            }
            let id = type_ident(&p.id);
            out.push_str(&format!("export interface {id} {{\n"));
            if let Some(ms) = methods.get(p.id.as_str()) {
                for m in ms {
                    out.push_str(m);
                }
            }
            out.push_str("}\n\n");
        }
        for n in &s.notes {
            out.push_str(&format!(
                "// note ({}): {}\n",
                note_placement(n.placement),
                n.text
            ));
        }
        if !s.notes.is_empty() {
            out.push('\n');
        }
    }

    fn emit_state(s: &StateDiagram, out: &mut String) {
        let variants: Vec<&str> = s
            .states
            .iter()
            .filter(|st| !matches!(st.kind, StateNodeKind::StartEnd))
            .map(|st| st.id.as_str())
            .collect();
        if variants.is_empty() {
            out.push_str("// state diagram has no states.\n");
            return;
        }
        out.push_str(&format!(
            "export type States = '{}';\n\n",
            variants.join("' | '")
        ));
        out.push_str("// transitions:\n");
        for t in &s.transitions {
            out.push_str(&format!(
                "//   '{}' -> '{}' : {}\n",
                t.from, t.to, t.label
            ));
        }
        out.push('\n');
    }

    fn emit_er(e: &ErDiagram, out: &mut String) {
        for ent in &e.entities {
            let id = type_ident(&ent.id);
            out.push_str(&format!("export interface {id} {{\n"));
            for a in &ent.attributes {
                let (_, marker) = er_attr_marker(a);
                out.push_str(&format!(
                    "    {marker} {}: {};\n",
                    ident(&a.name),
                    ts_type(&a.type_name)
                ));
            }
            out.push_str("}\n\n");
        }
        for r in &e.relationships {
            out.push_str(&format!(
                "// {} {}--{} {}\n",
                type_ident(&r.from),
                r.from_card.symbol(),
                r.to_card.symbol(),
                type_ident(&r.to),
            ));
        }
        if !e.relationships.is_empty() {
            out.push('\n');
        }
    }
}

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

/// Convert an arbitrary id into a valid Rust-style type / function identifier.
fn ident(id: &str) -> String {
    let mut out = String::with_capacity(id.len());
    for (i, c) in id.chars().enumerate() {
        let ok = c.is_ascii_alphanumeric() || c == '_';
        if ok && !(i == 0 && c.is_ascii_digit()) {
            out.push(c);
        } else if c == ' ' || c == '-' || c == '.' || c == '/' {
            out.push('_');
        }
    }
    if out.is_empty() {
        out.push('_');
    }
    out
}

/// Identifier for a type / module — starts with uppercase by convention.
fn type_ident(id: &str) -> String {
    let mut s = ident(id);
    if let Some(c) = s.chars().next()
        && c.is_ascii_lowercase()
    {
        s = c.to_ascii_uppercase().to_string() + &s[1..];
    }
    s
}

/// Identifier for a `mod` — mirrors `ident`.
fn mod_ident(id: &str) -> String {
    ident(id)
}

fn member_name(m: &ClassMember) -> String {
    let t = m.text.trim().trim_start_matches('+').trim();
    if let Some(idx) = t.find(['(', ':']) {
        t[..idx].trim().to_string()
    } else {
        t.to_string()
    }
}

/// Split `"Shape for Point"` → `Some(("Shape", "Point"))`.
/// Recognizes both `"X for Y"` and `"impl X"` shapes used by the Rust
/// extractor when no trait is present.
fn split_impl_id(id: &str) -> Option<(String, String)> {
    if let Some(rest) = id.strip_prefix("impl ") {
        return Some(("_".to_string(), rest.to_string()));
    }
    if let Some(idx) = id.find(" for ") {
        return Some((
            id[..idx].trim().to_string(),
            id[idx + 5..].trim().to_string(),
        ));
    }
    None
}

/// Parse `+name: Type` or `+name` → optional Rust field declaration body.
fn rust_field_decl(m: &ClassMember) -> Option<String> {
    let t = m.text.trim().trim_start_matches('+').trim();
    if t.contains('(') {
        return None;
    }
    if let Some(idx) = t.find(':') {
        let name = t[..idx].trim();
        let ty = t[idx + 1..].trim();
        Some(format!("{name}: {ty}"))
    } else if !t.is_empty() {
        Some(t.to_string())
    } else {
        None
    }
}

/// Parse `+name(args)` or `+name(args) Ret` → Rust method signature.
fn rust_method_sig(m: &ClassMember) -> Option<String> {
    let t = m.text.trim().trim_start_matches('+').trim();
    let open = t.find('(')?;
    let name = t[..open].trim();
    let close = t.rfind(')').unwrap_or(t.len());
    let args = t[open + 1..close].trim();
    let after = t[close + 1..].trim();
    let ret = if let Some(stripped) = after.strip_prefix("->") {
        stripped.trim()
    } else if let Some(stripped) = after.strip_prefix(':') {
        stripped.trim()
    } else {
        ""
    };
    Some(if ret.is_empty() {
        format!("fn {name}({args})")
    } else {
        format!("fn {name}({args}) -> {ret}")
    })
}

/// Parse a member into a TypeScript field declaration body (no semicolon).
fn ts_field_decl(m: &ClassMember) -> Option<String> {
    let t = m.text.trim().trim_start_matches('+').trim();
    if t.contains('(') {
        return None;
    }
    if let Some(idx) = t.find(':') {
        let name = t[..idx].trim();
        let ty = t[idx + 1..].trim().trim_start_matches(':').trim();
        Some(format!("{name}: {}", ts_type(ty)))
    } else if !t.is_empty() {
        Some(format!("{t}: unknown"))
    } else {
        None
    }
}

/// Parse a member into a TypeScript method signature.
/// `interface_mode` is accepted for symmetry with the Rust variant but
/// currently unused; both interface and class bodies use the same shape
/// (the body is omitted and the caller appends `;` or `{ … }`).
fn ts_method_sig(m: &ClassMember, _interface_mode: bool) -> Option<String> {
    let t = m.text.trim().trim_start_matches('+').trim();
    let open = t.find('(')?;
    let name = t[..open].trim();
    let close = t.rfind(')').unwrap_or(t.len());
    let args = t[open + 1..close].trim();
    let after = t[close + 1..].trim();
    let ret = if let Some(stripped) = after.strip_prefix(':') {
        stripped.trim()
    } else {
        ""
    };
    let ret_ts = if ret.is_empty() {
        "void".to_string()
    } else {
        ts_type(ret)
    };
    Some(format!("{name}({args}): {ret_ts}"))
}

fn ts_type(t: &str) -> String {
    let t = t.trim();
    if t.is_empty() {
        return "unknown".into();
    }
    match t {
        "i32" | "i64" | "u32" | "u64" | "usize" | "isize" | "f32" | "f64" => "number".into(),
        "bool" => "boolean".into(),
        "String" | "str" | "&str" => "string".into(),
        _ => t.to_string(),
    }
}

fn er_attr_marker(a: &Attribute) -> (String, &'static str) {
    let ty = ts_type(&a.type_name);
    let marker = if a.pk { "/// PK\n    " } else { "" };
    (ty, marker)
}

fn arrow_str(k: RelationKind) -> &'static str {
    k.mermaid_str()
}

fn cardinality(r: &Relation) -> String {
    match (&r.from_card, &r.to_card) {
        (Some(f), Some(t)) => format!("{f}..{t}"),
        (Some(f), None) => f.clone(),
        (None, Some(t)) => t.clone(),
        (None, None) => String::new(),
    }
}

fn field_for_relation(r: &Relation) -> String {
    format!("{}: {}", ident(&r.to), ident(&r.to))
}

fn style_arrow(s: &crate::diagram::EdgeStyle) -> &str {
    s.arrow_str()
}

fn note_placement(p: crate::sequence::NotePlacement) -> &'static str {
    match p {
        crate::sequence::NotePlacement::LeftOf => "left of",
        crate::sequence::NotePlacement::RightOf => "right of",
        crate::sequence::NotePlacement::Over => "over",
    }
}

fn node_label(n: &Node) -> String {
    if n.text.is_empty() {
        n.id.clone()
    } else {
        n.text.clone()
    }
}

#[allow(dead_code)]
fn cardinality_from(c: Cardinality) -> &'static str {
    c.symbol()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::Diagram;

    fn class_doc() -> Document {
        Document::single(Diagram::Class(crate::class::ClassDiagram {
            classes: vec![Class {
                id: "Point".into(),
                members: vec![
                    ClassMember {
                        text: "+x: f64".into(),
                    },
                    ClassMember {
                        text: "+y: f64".into(),
                    },
                    ClassMember {
                        text: "+translate(dx: f64, dy: f64)".into(),
                    },
                ],
                stereotype: Some("struct".into()),
            }],
            relations: vec![],
            notes: vec![],
        }))
    }

    #[test]
    fn rust_class_struct_with_fields_and_method() {
        let s = skeleton(&class_doc(), Language::Rust);
        assert!(s.contains("struct Point"), "missing struct: {s}");
        assert!(s.contains("pub x: f64"), "missing field x: {s}");
        assert!(s.contains("fn translate("), "missing method: {s}");
        assert!(s.contains("todo!()"), "missing body stub: {s}");
    }

    #[test]
    fn rust_interface_emits_trait() {
        let mut d = class_doc();
        if let Diagram::Class(c) = &mut d.diagrams[0] {
            c.classes[0].stereotype = Some("interface".into());
            c.classes[0].members = vec![ClassMember {
                text: "+area() -> f64".into(),
            }];
        }
        let s = skeleton(&d, Language::Rust);
        assert!(s.contains("trait Point"), "missing trait: {s}");
        assert!(s.contains("fn area"), "missing method: {s}");
    }

    #[test]
    fn rust_enum_emits_enum_variants() {
        let mut d = class_doc();
        if let Diagram::Class(c) = &mut d.diagrams[0] {
            c.classes[0].id = "Color".into();
            c.classes[0].stereotype = Some("enumeration".into());
            c.classes[0].members = vec![
                ClassMember { text: "+Red".into() },
                ClassMember { text: "+Green".into() },
            ];
        }
        let s = skeleton(&d, Language::Rust);
        assert!(s.contains("enum Color"), "missing enum: {s}");
        assert!(s.contains("Red,"), "missing variant: {s}");
        assert!(s.contains("Green,"), "missing variant: {s}");
    }

    #[test]
    fn rust_inheritance_emits_impl_block() {
        let mut d = class_doc();
        if let Diagram::Class(c) = &mut d.diagrams[0] {
            c.classes.push(Class {
                id: "Shape".into(),
                members: vec![],
                stereotype: Some("interface".into()),
            });
            c.relations.push(Relation {
                from: "Point".into(),
                to: "Shape".into(),
                kind: RelationKind::Realization,
                label: String::new(),
                from_card: None,
                to_card: None,
            });
        }
        let s = skeleton(&d, Language::Rust);
        assert!(
            s.contains("impl Shape for Point"),
            "missing impl block: {s}"
        );
    }

    #[test]
    fn ts_class_with_extends_and_implements() {
        let mut d = class_doc();
        if let Diagram::Class(c) = &mut d.diagrams[0] {
            c.classes[0].members = vec![ClassMember {
                text: "+translate(dx: number, dy: number): void".into(),
            }];
            c.classes.push(Class {
                id: "Shape".into(),
                members: vec![],
                stereotype: Some("interface".into()),
            });
            c.classes.push(Class {
                id: "Base".into(),
                members: vec![],
                stereotype: Some("class".into()),
            });
            c.relations.push(Relation {
                from: "Point".into(),
                to: "Base".into(),
                kind: RelationKind::Inheritance,
                label: String::new(),
                from_card: None,
                to_card: None,
            });
            c.relations.push(Relation {
                from: "Point".into(),
                to: "Shape".into(),
                kind: RelationKind::Realization,
                label: String::new(),
                from_card: None,
                to_card: None,
            });
        }
        let s = skeleton(&d, Language::TypeScript);
        assert!(s.contains("class Point extends Base implements Shape"), "head: {s}");
        assert!(s.contains("translate(dx: number"), "method: {s}");
        assert!(s.contains("interface Shape"), "shape: {s}");
    }

    #[test]
    fn flowchart_stadium_node_is_function() {
        let mut d = class_doc();
        d.diagrams[0] = Diagram::Flowchart(crate::diagram::Diagram {
            rankdir: "LR".into(),
            nodes: vec![Node {
                id: "compute".into(),
                text: "compute".into(),
                shape: NodeShape::Stadium,
                href: None,
                tooltip: None,
            }],
            edges: vec![],
            subgraphs: vec![],
            styles: vec![],
            class_defs: vec![],
            class_applies: vec![],
            link_styles: vec![],
        });
        let s = skeleton(&d, Language::Rust);
        assert!(s.contains("fn compute()"), "function missing: {s}");
        assert!(s.contains("todo!()"));
    }

    #[test]
    fn flowchart_subgraph_is_module() {
        let mut d = class_doc();
        d.diagrams[0] = Diagram::Flowchart(crate::diagram::Diagram {
            rankdir: "TD".into(),
            nodes: vec![
                Node {
                    id: "a".into(),
                    text: "a".into(),
                    shape: NodeShape::Stadium,
                    href: None,
                    tooltip: None,
                },
                Node {
                    id: "b".into(),
                    text: "b".into(),
                    shape: NodeShape::Stadium,
                    href: None,
                    tooltip: None,
                },
            ],
            edges: vec![crate::diagram::Edge {
                from: "a".into(),
                to: "b".into(),
                label: "calls".into(),
                style: crate::diagram::EdgeStyle::Arrow,
            }],
            subgraphs: vec![crate::diagram::Subgraph {
                id: "grp".into(),
                nodes: vec!["a".into(), "b".into()],
            }],
            styles: vec![],
            class_defs: vec![],
            class_applies: vec![],
            link_styles: vec![],
        });
        let s = skeleton(&d, Language::Rust);
        assert!(s.contains("pub mod grp"), "mod missing: {s}");
        assert!(s.contains("// a --> b // calls"), "edge comment: {s}");
    }
}