pub mod analyze;
pub mod class;
pub mod composite;
pub mod diagram;
pub mod embed;
pub mod er;
pub mod formats;
pub mod gantt;
pub mod generate;
pub mod ir;
pub mod layout;
pub mod lossiness;
pub mod markdown;
pub mod parser;
pub mod renderer;
pub mod sequence;
pub mod state;

#[cfg(feature = "native")]
pub mod cli;
#[cfg(feature = "native")]
pub mod mcp;
#[cfg(feature = "native")]
pub mod pdf;
#[cfg(feature = "native")]
pub mod png;
#[cfg(feature = "native")]
pub mod preview;

#[cfg(feature = "wasm")]
pub mod wasm;
